use TicTacToeDB;

-- MySQL Script generated by MySQL Workbench
-- Sat Nov 12 12:30:11 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema tictactoedb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema tictactoedb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tictactoedb` DEFAULT CHARACTER SET utf8 ;
USE `tictactoedb` ;

-- -----------------------------------------------------
-- Table `tictactoedb`.`Game`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tictactoedb`.`Game` ;

CREATE TABLE IF NOT EXISTS `tictactoedb`.`Game` (
  `category_id` INT NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`category_id`));


-- -----------------------------------------------------
-- Table `tictactoedb`.`User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tictactoedb`.`User` ;

CREATE TABLE IF NOT EXISTS `tictactoedb`.`User` (
  `username` VARCHAR(16) NOT NULL,
  `email` VARCHAR(255) NULL,
  `password` VARCHAR(32) NOT NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
